"""Module to store constants.

Mapping of metabolite names to a standardized format.
Used to normalize data from different sources.
"""

NAME_MAP = {
    "Acetil-L-carnitina": "ACETIL-L-CARNITINA",
    "Adenosina": "ADENOSINA",
    "ADMA": "Dimetilarginina Assimétrica [ADMA]",
    "Alanina": "ALANINA",
    "Arginina": "ARGININA",
    "Asparagina": "ASPARAGINA",
    "Aspartato": "ASPARTATO",
    "Butiril-L-carnitina": "BUTIRIL-L-CARNITINA",
    "L-carnitina": "L-CARNITINA",
    "Alfa-cetoglutarato": "ALFA-CETOGLUTARATO",
    "Cisteina": "CISTEÍNA",
    "Cistina": "CISTINA",
    "Citrulina": "CITRULINA",
    "Fenilalanina": "FENILALANINA",
    "GABA": "GABA",
    "Glicina": "GLICINA",
    "Glutamato": "GLUTAMATO",
    "Glutamina": "GLUTAMINA",
    "Glutationa oxidada": "GLUTATIONA OXIDADA (GSSG)",
    "Glutationa reduzida": "GLUTATIONA REDUZIDA (GSH)",
    "Glutationa total (Entra no TNM)": "GLUTATIONA TOTAL",
    "Guanosina": "GUANOSINA",
    "4-Hidroxiprolina": "4-HIDROXIPROLINA",
    "Histidina": "HISTIDINA",
    "Isoleucina": "ISOLEUCINA",
    "Isovaleril-L-carnitina": "ISOVALERIL-L-CARNITINA",
    "Lactato": "LACTATO",
    "Leucina": "LEUCINA",
    "Lisina": "LISINA",
    "Malato": "MALATO",
    "Metionina": "METIONINA",
    "Ornitina": "ORNITINA",
    "Palmitoil-L-carnitina": "PALMITOIL-L-CARNITINA [C16]",
    "Piruvato": "PIRUVATO",
    "Prolina": "PROLINA",
    "Propionil-L-carnitina": "PROPIONIL-L-CARNITINA [C3]",
    "Quinurenina": "QUINURENINA",
    "Serina": "SERINA",
    "Succinato": "SUCCINATO",
    "Taurina": "TAURINA",
    "Tetradecanoil-L-carnitina": "TETRADECANOIL-L-CARNITINA",
    "Timina": "TIMINA",
    "Tirosina": "TIROSINA",
    "TMAO (triometilamina -N-oxido)": "TMAO [Trimetilamina N-Óxido]",
    "Treonina": "TREONINA",
    "Triptofano": "TRIPTOFANO",
    "Ácido úrico": "ÁCIDO ÚRICO",
    "Valina": "VALINA",
    "1-Estearoil-2-araquidonoil-fosfatidilcolina": "1-ESTEREAROIL-2-ARAQUIDONOIL-FOSFATIDILCOLINA",
    "1-Estearoil-2-linoleoil-fosfatidilcolina": "1-ESTEAROIL-2-LINOLEOIL-FOSFATIDILCOLINA",
    "1-Estearoil-lisofosfatidilcolina": "1-ESTEAROIL-LISOFOSFATIDILCOLINA [HDL]",
    "1-Oleil-lisofosfatidilcolina": "1-OLEIL-LISOFOSFATIDILCOLINA [N9]",
    "1-Oleoil-2-estearoil-fosfatidilcolina": "1-OLEOIL-2-ESTEAROIL-FOSFATIDILCOLINA [9]",
    "1-Palmitoil-2-araquidonoil-fosfatidilcolina (LDL oxidada)": "1-PALMITOIL-2-ARAQUIDONOIL-FOSFATIDILCOLINA [LDL OX.]",
    "1-Palmitoil-2-docosaexenoil-fosfatidilcolina": "1-PALMITOIL-2-DOCOSAEXENOIL-FOSFATIDILCOLINA [3]",
    "1-Pamitoil-2-linoleoil-fosfatidilcolina": "1-PALMITOIL-2-LINOLEOIL-FOSFATIDILCOLINA",
}
