"""Domain models for medical and nutritional reports.

This module contains Pydantic models that define the structure of medical and
nutritional reports, including findings, recommendations, and various data items
used throughout the IonNutri and VidaNova reporting systems.
"""

from datetime import datetime

from pydantic import BaseModel, Field


# Itens básicos
class FindingItem(BaseModel):
    """Modelo que representa um achado específico."""

    status: str = Field(..., description="Status do achado (normal, alterado)")
    description: str = Field(..., description="Descrição do achado")
    metabolite: str = Field(..., description="Nome do metabólito associado")
    implications: list[str] = Field(..., description="Implicações do achado")


class DeficiencyItem(BaseModel):
    """Modelo que representa uma deficiência nutricional."""

    nutrient: str = Field(..., description="Nutriente deficiente")
    description: str = Field(..., description="Descrição da deficiência")
    symptoms: list[str] = Field(..., description="Sintomas associados")
    recommendations: list[str] = Field(..., description="Recomendações para correção")
    # level: float = Field(..., description="Nível atual")                  # Se for determinado pelas regras de negócio talvez não seja necessário
    # reference_range: str = Field(..., description="Faixa de referência")  # Aqui também


class ExamItem(BaseModel):
    """Modelo que representa um item de exame."""

    name: str = Field(..., description="Nome do exame")
    purpose: str = Field(..., description="Finalidade do exame")
    urgency: str = Field(..., description="Urgência do exame")
    # result: str = Field(..., description="Resultado do exame")
    # reference: str = Field(..., description="Referência para o resultado")
    # observation: Optional[str] = Field(None, description="Observações sobre o exame")


# Itens de recomendação
class SupplementItem(BaseModel):
    """Modelo que representa uma recomendação de suplemento."""

    name: str = Field(..., description="Nome do suplemento")
    dosage: str = Field(..., description="Dosagem recomendada")
    frequency: str = Field(..., description="Frequência de consumo")
    purpose: str = Field(..., description="Finalidade do suplemento")
    # duration: Optional[str] = Field(None, description="Duração do tratamento")
    observation: str | None = Field(None, description="Observações adicionais")


class FoodItem(BaseModel):
    """Modelo que representa uma recomendação alimentar."""

    name: str = Field(..., description="Nome do alimento")
    quantity: str = Field(..., description="Quantidade recomendada")
    frequency: str = Field(..., description="Frequência de consumo")
    # benefits: List[str] = Field(..., description="Benefícios do alimento")
    observation: str | None = Field(None, description="Observações adicionais")


class LifestyleItem(BaseModel):
    """Modelo que representa uma recomendação de estilo de vida."""

    category: str = Field(..., description="Categoria (exercício, sono, etc.)")
    description: str = Field(..., description="Descrição da recomendação")
    rationale: str = Field(..., description="Justificativa da recomendação")
    # expected_benefits: List[str] = Field(..., description="Benefícios esperados") # Não cabe a mim dizer se é válido, mas pode agregar valor ao produto


# Seções
class FindingsSection(BaseModel):
    """Modelo que representa a seção de achados do relatório."""

    items: list[FindingItem] = Field(..., description="Lista de achados")
    conclusion: str = Field(..., description="Conclusão dos achados")


class NutritionalRecs(BaseModel):
    """Modelo que representa recomendações nutricionais."""

    energetics: list[FoodItem] = Field(
        ..., description="Recomendações de carboidratos e fontes energéticas."
    )
    constructors: list[FoodItem] = Field(
        ..., description="Recomendações de proteínas (construtores)."
    )
    regulators: list[FoodItem] = Field(
        ..., description="Recomendações de vitaminas e minerais (reguladores)."
    )
    fats: list[FoodItem] = Field(
        ..., description="Recomendações de lipídios (gorduras saudáveis)."
    )


class RecommendationsSection(BaseModel):
    """Modelo que representa a seção de recomendações do relatório."""

    nutritional: NutritionalRecs = Field(..., description="Recomendações nutricionais")
    lifestyle: list[LifestyleItem] = Field(
        ..., description="Recomendações de estilo de vida"
    )
    supplements: list[SupplementItem] = Field(
        ..., description="Recomendações de suplementos"
    )
    # follow_up: str = Field(..., description="Orientações para acompanhamento")


# SCHEMAS PARA SAÍDA DO LLM
class SummaryContent(BaseModel):
    """Model for summary content generated by LLM."""

    content: str = Field(..., description="Conteúdo textual de um resumo.")


class GeneralGuidelinesContent(BaseModel):
    """Model for general guidelines content generated by LLM."""

    content: str = Field(..., description="Conteúdo textual de diretrizes gerais.")


class ClosingNoteContent(BaseModel):
    """Model for closing note content generated by LLM."""

    content: str = Field(..., description="Conteúdo textual da nota de encerramento.")


class MarkdownReport(BaseModel):
    """Model for Markdown report content generated by LLM."""

    content: str = Field(..., description="Conteúdo Markdown report.")


# Wrappers para listas de itens que o LLM gera
class FoodRecommendationSectionWrapper(BaseModel):
    """Wrapper for food recommendation items generated by LLM."""

    items: list[FoodItem] = Field(
        ..., description="Lista de recomendações de alimentos."
    )


class LifestyleRecommendationSectionWrapper(BaseModel):
    """Wrapper for lifestyle recommendation items generated by LLM."""

    items: list[LifestyleItem] = Field(
        ..., description="Lista de recomendações de estilo de vida."
    )


class SupplementRecommendationSectionWrapper(BaseModel):
    """Wrapper for supplement recommendation items generated by LLM."""

    items: list[SupplementItem] = Field(
        ..., description="Lista de recomendações de suplementos."
    )


class DeficiencyRecommendationSectionWrapper(BaseModel):
    """Wrapper for nutritional deficiency items generated by LLM."""

    items: list[DeficiencyItem] = Field(
        ..., description="Lista de deficiências nutricionais."
    )


class ExamsRecommendationSectionWrapper(BaseModel):
    """Wrapper for additional exam items generated by LLM."""

    items: list[ExamItem] = Field(..., description="Lista de exames adicionais.")


class FitnessRecommendation(BaseModel):
    """Model for fitness and performance recommendations.

    Attributes:
        overall_assessment (str): General fitness assessment.
        physical_activities (list[LifestyleItem]): Physical activity suggestions.
        diet_strategies (list[FoodItem]): Healthy nutrition strategies.
        recovery_tips (str): Recovery and rest recommendations.

    """

    overall_assessment: str = Field(
        ..., description="Avaliação geral do condicionamento físico."
    )
    physical_activities: list[LifestyleItem] = Field(
        ..., description="Sugestões de atividades físicas."
    )
    diet_strategies: list[FoodItem] = Field(
        ..., description="Estratégias de alimentação saudável."
    )
    recovery_tips: str = Field(..., description="Dicas de recuperação.")


class BaseReport(BaseModel):
    """Modelo base com campos compartilhados entre relatórios."""

    report_id: str = Field(..., description="ID do relatório")
    patient_id: str = Field(..., description="ID do paciente")
    anamnesis_id: str = Field(..., description="ID da anamnese")
    exam_id: str = Field(..., description="ID do exame")
    version: str = Field(..., description="Versão do relatório")
    timestamp: datetime = Field(..., description="Data e hora da geração do relatório")

    summary: SummaryContent = Field(..., description="Resumo geral do relatório")
    findings: FindingsSection = Field(..., description="Achados clínicos relevantes")


class IonNutriReport(BaseReport):
    """Modelo que representa um relatório completo de anamnese e exames."""

    recommendations: RecommendationsSection = Field(
        ..., description="Seção de recomendações"
    )
    deficiencies: list[DeficiencyItem] = Field(
        ..., description="Lista de deficiências nutricionais"
    )
    general_guidelines: str = Field(
        ..., description="Diretrizes gerais para o paciente"
    )
    additional_exams: list[ExamItem] = Field(
        ..., description="Exames adicionais recomendados"
    )


# VidaNova specific models
class VidaNovaDietSuggestions(BaseModel):
    """Diet suggestions for all diet types in VidaNova reports."""

    carnivoro_onivoro: list[str] = Field(
        ..., description="Sugestões alimentares para dieta carnívora/onívora"
    )
    vegetariano: list[str] = Field(
        ..., description="Sugestões alimentares para dieta vegetariana"
    )
    vegano: list[str] = Field(
        ..., description="Sugestões alimentares para dieta vegana"
    )


class TrainingRecommendation(BaseModel):
    """Training recommendations for VidaNova reports."""

    recommendations: list[str] = Field(
        ..., description="Lista de recomendações de treino"
    )
    avoid: list[str] = Field(..., description="Lista de atividades a evitar")
    focus: str = Field(..., description="Foco principal do treino")


class VidaNovaReport(BaseReport):
    """Modelo de relatório para o plugin VidaNova, seguindo estrutura do template."""

    summary: SummaryContent = Field(..., description="Resumo do relatório")
    findings: FindingsSection = Field(..., description="Achados clínicos")
    diet_suggestions: VidaNovaDietSuggestions = Field(
        ..., description="Sugestões alimentares por tipo de dieta"
    )
    supplements: list[SupplementItem] = Field(
        ..., description="Lista de suplementações recomendadas"
    )
    training: TrainingRecommendation = Field(
        ..., description="Recomendações de treino e atividade física"
    )
